### ISSUE TITLE
Link to 404 error code in section 3 of https://chrysalis.docs.iota.org/introduction/path_to_chrysalis.html

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/chrysalis-docs#19]
The link on chrysalis.docs.iota.org/introduction/path_to_chrysalis - specification and standartization "milestone selection"  - https://github.com/Wollac/protocol-rfcs/blob/milestone-merkle-validation/text/0012-milestone-merkle-validation/0012-milestone-merkle-validation.md leads to an 404 error code webpage.

Correct link should be this:
https://github.com/iotaledger/protocol-rfcs/blob/milestone-merkle-validation-chrysalis-pt-2/text/0012-milestone-merkle-validation/0012-milestone-merkle-validation.md

![image](https://user-images.githubusercontent.com/77154511/108748697-d6ca3200-7579-11eb-97aa-93c507bf81a5.png)

**Comment by huhn511** [comment]
Fixed with #20
